### ISSUE TITLE
Showing user profile feature

### ISSUE THREAD

**Issue by wzieba** [pszklarska/FlutterGitHub#1]
Hi Paulina, thanks for this repo - I consider this as a very readable and smooth start in Flutter.io world.

I see there are few features you've left for future - do you mind if I contribute in 

> Showing user profile

?

**Comment by wzieba** [comment]
I've finally managed to finish this PR, please take a look in free time @pszklarska 😃

**Comment by pszklarska** [comment]
Cool, thanks! Closed 🙂
